### ISSUE TITLE
Build a basic web page Using Github Pages.

### ISSUE THREAD

**Issue by lakshay4040** [USoC2020/Multi-linguistic_Podcast_Platform#10]
- Use your personal Github account to create a repository for this task, and enable the GITHUB PAGES option from settings. 
- Now create a basic layout of a web page and add your introduction.
- Take a screenshot of the webpage and rename it with your Github username.
- Now, add this screenshot to the folder named "Screenshots" in the project repository- ** "Multi-Linguistic_Podcast_Platform."**
**- Make sure that no other file containing your introduction, else than a screenshot should be added to the project repository. **

**Comment by AakarshitAgarwal** [comment]
I would like to work on this issue.

**Comment by ragharwal** [comment]
okay.
