### ISSUE TITLE
Add functionality for translating Speech to Text.

### ISSUE THREAD

**Issue by lakshay4040** [USoC2020/Multi-linguistic_Podcast_Platform#19]
The most lucrative concept of this platform will be the translation of podcasts into various languages. So, a functionality to translating the audio/speech to text will be the first job.

Use the **SPEECH-RECOGNITION** in python (Google's speech recognition/IBM Speech to Text APIs) to build a code for the same.

Once the code is ready, add it in the folder named **podcast_translate** in the project repository.

In your code, include the complete procedure of execution as well.

**Comment by ishrep** [comment]
I would like to work on this
